; Listing generated by Microsoft (R) Optimizing Compiler Version 19.27.29111.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__F66CEB67_corecrt_stdio_config@h DB 01H
__101834BA_corecrt_wstdio@h DB 01H
__AD6A91B7_stdio@h DB 01H
__F7309570_SDL_stdinc@h DB 01H
__DEF1ED59_SDL_endian@h DB 01H
__09340588_corecrt_math@h DB 01H
__B0C4CEA9_malloc@h DB 01H
__D291391D_SDL_rect@h DB 01H
__367CC694_corecrt_memcpy_s@h DB 01H
__DC9673E3_corecrt_wstring@h DB 01H
__A29A7DFB_string@h DB 01H
__45F4AF76_corecrt_wtime@h DB 01H
__8AA3BE86_time@h DB 01H
__8BF91AE9_main@c DB 01H
msvcjmc	ENDS
PUBLIC	__local_stdio_printf_options
PUBLIC	_vfprintf_l
PUBLIC	printf
PUBLIC	SDL_main
PUBLIC	error_msg
PUBLIC	animation_create
PUBLIC	animation_animate
PUBLIC	animation_step_forward
PUBLIC	animation_draw
PUBLIC	animation_free_frames
PUBLIC	__JustMyCode_Default
PUBLIC	??_C@_0M@KMABGBDJ@Error?3?5?$CFs?5?6@		; `string'
PUBLIC	??_C@_0BJ@JPHBGNOG@Could?5not?5Initialise?5SDL@	; `string'
PUBLIC	??_C@_04BLKNCPFJ@Lama@				; `string'
PUBLIC	??_C@_0BK@OADPNOMO@Could?5not?5initialise?5grid@ ; `string'
PUBLIC	??_C@_02JDPG@rb@				; `string'
PUBLIC	??_C@_0M@INKEKBKD@texture?4bmp@			; `string'
PUBLIC	??_C@_0BC@DPMPNCOK@Surface?5not?5valid@		; `string'
EXTRN	__imp_calloc:PROC
EXTRN	__imp_free:PROC
EXTRN	__imp_malloc:PROC
EXTRN	__imp_srand:PROC
EXTRN	__imp___acrt_iob_func:PROC
EXTRN	__imp___stdio_common_vfprintf:PROC
EXTRN	SDL_RWFromFile:PROC
EXTRN	SDL_FreeSurface:PROC
EXTRN	SDL_LoadBMP_RW:PROC
EXTRN	SDL_SetColorKey:PROC
EXTRN	SDL_CreateWindow:PROC
EXTRN	SDL_GetMouseState:PROC
EXTRN	SDL_PollEvent:PROC
EXTRN	SDL_CreateRenderer:PROC
EXTRN	SDL_CreateTextureFromSurface:PROC
EXTRN	SDL_SetRenderDrawColor:PROC
EXTRN	SDL_RenderClear:PROC
EXTRN	SDL_RenderFillRect:PROC
EXTRN	SDL_RenderCopy:PROC
EXTRN	SDL_RenderPresent:PROC
EXTRN	SDL_Init:PROC
EXTRN	SDL_Quit:PROC
EXTRN	memset:PROC
EXTRN	__imp__localtime64_s:PROC
EXTRN	__imp__time64:PROC
EXTRN	grid_init:PROC
EXTRN	grid_draw:PROC
EXTRN	grid_free_nodes:PROC
EXTRN	grass_field_init:PROC
EXTRN	grass_field_update:PROC
EXTRN	grass_field_toggle_active_at:PROC
EXTRN	grass_field_draw:PROC
EXTRN	grass_field_clean:PROC
EXTRN	_RTC_CheckStackVars:PROC
EXTRN	_RTC_InitBase:PROC
EXTRN	_RTC_Shutdown:PROC
EXTRN	__CheckForDebuggerJustMyCode:PROC
EXTRN	__GSHandlerCheck:PROC
EXTRN	__security_check_cookie:PROC
EXTRN	__security_cookie:QWORD
_DATA	SEGMENT
COMM	?_OptionsStorage@?1??__local_stdio_printf_options@@9@9:QWORD							; `__local_stdio_printf_options'::`2'::_OptionsStorage
_DATA	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$__local_stdio_printf_options DD imagerel $LN3
	DD	imagerel $LN3+59
	DD	imagerel $unwind$__local_stdio_printf_options
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$_vfprintf_l DD imagerel $LN3
	DD	imagerel $LN3+126
	DD	imagerel $unwind$_vfprintf_l
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$printf DD imagerel $LN3
	DD	imagerel $LN3+189
	DD	imagerel $unwind$printf
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$SDL_main DD imagerel $LN16
	DD	imagerel $LN16+1599
	DD	imagerel $unwind$SDL_main
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$time DD	imagerel time
	DD	imagerel time+77
	DD	imagerel $unwind$time
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$localtime_s DD imagerel localtime_s
	DD	imagerel localtime_s+89
	DD	imagerel $unwind$localtime_s
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$error_msg DD imagerel $LN3
	DD	imagerel $LN3+88
	DD	imagerel $unwind$error_msg
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$animation_create DD imagerel $LN9
	DD	imagerel $LN9+451
	DD	imagerel $unwind$animation_create
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$animation_animate DD imagerel $LN4
	DD	imagerel $LN4+149
	DD	imagerel $unwind$animation_animate
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$animation_step_forward DD imagerel $LN3
	DD	imagerel $LN3+114
	DD	imagerel $unwind$animation_step_forward
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$animation_draw DD imagerel $LN3
	DD	imagerel $LN3+180
	DD	imagerel $unwind$animation_draw
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$animation_free_frames DD imagerel $LN4
	DD	imagerel $LN4+95
	DD	imagerel $unwind$animation_free_frames
pdata	ENDS
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
_RTC_Shutdown.rtc$TMZ DQ FLAT:_RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
_RTC_InitBase.rtc$IMZ DQ FLAT:_RTC_InitBase
rtc$IMZ	ENDS
;	COMDAT ??_C@_0BC@DPMPNCOK@Surface?5not?5valid@
CONST	SEGMENT
??_C@_0BC@DPMPNCOK@Surface?5not?5valid@ DB 'Surface not valid', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0M@INKEKBKD@texture?4bmp@
CONST	SEGMENT
??_C@_0M@INKEKBKD@texture?4bmp@ DB 'texture.bmp', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_02JDPG@rb@
CONST	SEGMENT
??_C@_02JDPG@rb@ DB 'rb', 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_0BK@OADPNOMO@Could?5not?5initialise?5grid@
CONST	SEGMENT
??_C@_0BK@OADPNOMO@Could?5not?5initialise?5grid@ DB 'Could not initialise'
	DB	' grid', 00H					; `string'
CONST	ENDS
;	COMDAT ??_C@_04BLKNCPFJ@Lama@
CONST	SEGMENT
??_C@_04BLKNCPFJ@Lama@ DB 'Lama', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0BJ@JPHBGNOG@Could?5not?5Initialise?5SDL@
CONST	SEGMENT
??_C@_0BJ@JPHBGNOG@Could?5not?5Initialise?5SDL@ DB 'Could not Initialise '
	DB	'SDL', 00H					; `string'
CONST	ENDS
;	COMDAT ??_C@_0M@KMABGBDJ@Error?3?5?$CFs?5?6@
CONST	SEGMENT
??_C@_0M@KMABGBDJ@Error?3?5?$CFs?5?6@ DB 'Error: %s ', 0aH, 00H ; `string'
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$animation_free_frames DD 025052a01H
	DD	010e2313H
	DD	07007001dH
	DD	05006H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$animation_draw DD 035053401H
	DD	0118331dH
	DD	07011001fH
	DD	05010H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$animation_step_forward DD 025052a01H
	DD	010e2313H
	DD	07007001dH
	DD	05006H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$animation_animate DD 025052a01H
	DD	010e2313H
	DD	07007001dH
	DD	05006H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$animation_create DD 025063a01H
	DD	011e2323H
	DD	07017002cH
	DD	050156016H
xdata	ENDS
;	COMDAT CONST
CONST	SEGMENT
animation_create$rtcName$0 DB 061H
	DB	06eH
	DB	069H
	DB	06dH
	DB	00H
	ORG $+11
animation_create$rtcVarDesc DD 028H
	DD	020H
	DQ	FLAT:animation_create$rtcName$0
	ORG $+48
animation_create$rtcFrameData DD 01H
	DD	00H
	DQ	FLAT:animation_create$rtcVarDesc
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$error_msg DD 025052a01H
	DD	010e2313H
	DD	07007001dH
	DD	05006H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$localtime_s DD 025052f01H
	DD	01132318H
	DD	0700c001dH
	DD	0500bH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$time DD	025052a01H
	DD	010e2313H
	DD	07007001dH
	DD	05006H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$SDL_main DD 045063f19H
	DD	01134318H
	DD	0700c00deH
	DD	0500a600bH
	DD	imagerel __GSHandlerCheck
	DD	06e8H
xdata	ENDS
;	COMDAT CONST
CONST	SEGMENT
SDL_main$rtcName$0 DB 06dH
	DB	06fH
	DB	075H
	DB	073H
	DB	065H
	DB	05fH
	DB	069H
	DB	06eH
	DB	070H
	DB	075H
	DB	074H
	DB	00H
SDL_main$rtcName$4 DB 061H
	DB	070H
	DB	070H
	DB	00H
SDL_main$rtcName$1 DB 077H
	DB	069H
	DB	06eH
	DB	064H
	DB	06fH
	DB	077H
	DB	05fH
	DB	073H
	DB	065H
	DB	074H
	DB	074H
	DB	069H
	DB	06eH
	DB	067H
	DB	073H
	DB	00H
SDL_main$rtcName$2 DB 065H
	DB	076H
	DB	065H
	DB	06eH
	DB	074H
	DB	00H
	ORG $+2
SDL_main$rtcName$3 DB 06dH
	DB	06fH
	DB	075H
	DB	073H
	DB	065H
	DB	05fH
	DB	070H
	DB	06fH
	DB	073H
	DB	069H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	05fH
	DB	06fH
	DB	06eH
	DB	05fH
	DB	067H
	DB	072H
	DB	069H
	DB	064H
	DB	00H
	ORG $+1
SDL_main$rtcName$5 DB 067H
	DB	072H
	DB	069H
	DB	064H
	DB	05fH
	DB	06cH
	DB	061H
	DB	079H
	DB	065H
	DB	072H
	DB	00H
	ORG $+5
SDL_main$rtcName$6 DB 062H
	DB	061H
	DB	063H
	DB	06bH
	DB	067H
	DB	072H
	DB	06fH
	DB	075H
	DB	06eH
	DB	064H
	DB	05fH
	DB	063H
	DB	06fH
	DB	06cH
	DB	06fH
	DB	072H
	DB	00H
	ORG $+7
SDL_main$rtcName$7 DB 067H
	DB	072H
	DB	061H
	DB	073H
	DB	073H
	DB	05fH
	DB	073H
	DB	06fH
	DB	075H
	DB	072H
	DB	063H
	DB	065H
	DB	05fH
	DB	072H
	DB	065H
	DB	063H
	DB	074H
	DB	00H
	ORG $+6
SDL_main$rtcName$8 DB 067H
	DB	072H
	DB	061H
	DB	073H
	DB	073H
	DB	05fH
	DB	070H
	DB	06fH
	DB	06fH
	DB	06cH
	DB	00H
	ORG $+5
SDL_main$rtcName$9 DB 072H
	DB	061H
	DB	077H
	DB	074H
	DB	069H
	DB	06dH
	DB	065H
	DB	00H
SDL_main$rtcName$10 DB 067H
	DB	072H
	DB	061H
	DB	073H
	DB	073H
	DB	05fH
	DB	069H
	DB	06eH
	DB	064H
	DB	065H
	DB	078H
	DB	00H
SDL_main$rtcName$11 DB 072H
	DB	065H
	DB	063H
	DB	074H
	DB	073H
	DB	00H
	ORG $+6
SDL_main$rtcName$12 DB 064H
	DB	065H
	DB	073H
	DB	074H
	DB	069H
	DB	06eH
	DB	061H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	00H
SDL_main$rtcName$13 DB 061H
	DB	06eH
	DB	069H
	DB	06dH
	DB	00H
	ORG $+7
SDL_main$rtcFrameData DD 0eH
	DD	00H
	DQ	FLAT:SDL_main$rtcVarDesc
	ORG $+8
SDL_main$rtcVarDesc DD 0408H
	DD	020H
	DQ	FLAT:SDL_main$rtcName$13
	DD	03d8H
	DD	010H
	DQ	FLAT:SDL_main$rtcName$12
	DD	0370H
	DD	050H
	DQ	FLAT:SDL_main$rtcName$11
	DD	0348H
	DD	08H
	DQ	FLAT:SDL_main$rtcName$10
	DD	0248H
	DD	08H
	DQ	FLAT:SDL_main$rtcName$9
	DD	0208H
	DD	028H
	DQ	FLAT:SDL_main$rtcName$8
	DD	01d8H
	DD	010H
	DQ	FLAT:SDL_main$rtcName$7
	DD	0194H
	DD	04H
	DQ	FLAT:SDL_main$rtcName$6
	DD	0158H
	DD	020H
	DQ	FLAT:SDL_main$rtcName$5
	DD	0118H
	DD	020H
	DQ	FLAT:SDL_main$rtcName$4
	DD	0f8H
	DD	08H
	DQ	FLAT:SDL_main$rtcName$3
	DD	0a8H
	DD	038H
	DQ	FLAT:SDL_main$rtcName$2
	DD	078H
	DD	018H
	DQ	FLAT:SDL_main$rtcName$1
	DD	048H
	DD	0cH
	DQ	FLAT:SDL_main$rtcName$0
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$printf DD 025054a19H
	DD	011d2322H
	DD	070160025H
	DD	05015H
	DD	imagerel __GSHandlerCheck
	DD	0118H
xdata	ENDS
;	COMDAT CONST
CONST	SEGMENT
printf$rtcName$0 DB 05fH
	DB	041H
	DB	072H
	DB	067H
	DB	04cH
	DB	069H
	DB	073H
	DB	074H
	DB	00H
	ORG $+7
printf$rtcVarDesc DD 048H
	DD	08H
	DQ	FLAT:printf$rtcName$0
	ORG $+48
printf$rtcFrameData DD 01H
	DD	00H
	DQ	FLAT:printf$rtcVarDesc
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$_vfprintf_l DD 035053901H
	DD	011d3322H
	DD	07016001fH
	DD	05015H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$__local_stdio_printf_options DD 025051e01H
	DD	010a230fH
	DD	07003001dH
	DD	05002H
xdata	ENDS
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File E:\CPP-Programming\Lama\Lama\Lama\main.c
;	COMDAT animation_free_frames
_TEXT	SEGMENT
p_anim$ = 224
animation_free_frames PROC				; COMDAT

; 110  : {

$LN4:
	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	push	rdi
	sub	rsp, 232				; 000000e8H
	lea	rbp, QWORD PTR [rsp+32]
	mov	rdi, rsp
	mov	ecx, 58					; 0000003aH
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	rcx, QWORD PTR [rsp+264]
	lea	rcx, OFFSET FLAT:__8BF91AE9_main@c
	call	__CheckForDebuggerJustMyCode

; 111  :     if(p_anim->frames)

	mov	rax, QWORD PTR p_anim$[rbp]
	cmp	QWORD PTR [rax+16], 0
	je	SHORT $LN2@animation_

; 112  :         free(p_anim->frames);

	mov	rax, QWORD PTR p_anim$[rbp]
	mov	rcx, QWORD PTR [rax+16]
	call	QWORD PTR __imp_free
$LN2@animation_:

; 113  : }

	lea	rsp, QWORD PTR [rbp+200]
	pop	rdi
	pop	rbp
	ret	0
animation_free_frames ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File E:\CPP-Programming\Lama\Lama\Lama\main.c
;	COMDAT animation_draw
_TEXT	SEGMENT
p_renderer$ = 224
p_anim$ = 232
dest$ = 240
animation_draw PROC					; COMDAT

; 100  : {

$LN3:
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	push	rdi
	sub	rsp, 248				; 000000f8H
	lea	rbp, QWORD PTR [rsp+48]
	mov	rdi, rsp
	mov	ecx, 62					; 0000003eH
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	rcx, QWORD PTR [rsp+280]
	lea	rcx, OFFSET FLAT:__8BF91AE9_main@c
	call	__CheckForDebuggerJustMyCode

; 101  :     SDL_RenderCopy(p_renderer, p_anim->texture, &p_anim->current->rect, dest);

	mov	rax, QWORD PTR p_anim$[rbp]
	mov	rax, QWORD PTR [rax+8]
	mov	r9, QWORD PTR dest$[rbp]
	mov	r8, rax
	mov	rax, QWORD PTR p_anim$[rbp]
	mov	rdx, QWORD PTR [rax]
	mov	rcx, QWORD PTR p_renderer$[rbp]
	call	SDL_RenderCopy

; 102  : 
; 103  :     SDL_SetRenderDrawColor(p_renderer, 0, 255, 0, 255);

	mov	BYTE PTR [rsp+32], 255			; 000000ffH
	xor	r9d, r9d
	mov	r8b, 255				; 000000ffH
	xor	edx, edx
	mov	rcx, QWORD PTR p_renderer$[rbp]
	call	SDL_SetRenderDrawColor

; 104  :     SDL_RenderFillRect(p_renderer, &p_anim->current->rect);

	mov	rax, QWORD PTR p_anim$[rbp]
	mov	rax, QWORD PTR [rax+8]
	mov	rdx, rax
	mov	rcx, QWORD PTR p_renderer$[rbp]
	call	SDL_RenderFillRect

; 105  : 
; 106  :     animation_animate(p_anim);

	mov	rcx, QWORD PTR p_anim$[rbp]
	call	animation_animate

; 107  : }

	lea	rsp, QWORD PTR [rbp+200]
	pop	rdi
	pop	rbp
	ret	0
animation_draw ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File E:\CPP-Programming\Lama\Lama\Lama\main.c
;	COMDAT animation_step_forward
_TEXT	SEGMENT
p_anim$ = 224
animation_step_forward PROC				; COMDAT

; 94   : {

$LN3:
	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	push	rdi
	sub	rsp, 232				; 000000e8H
	lea	rbp, QWORD PTR [rsp+32]
	mov	rdi, rsp
	mov	ecx, 58					; 0000003aH
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	rcx, QWORD PTR [rsp+264]
	lea	rcx, OFFSET FLAT:__8BF91AE9_main@c
	call	__CheckForDebuggerJustMyCode

; 95   :     p_anim->current = p_anim->current->next;

	mov	rax, QWORD PTR p_anim$[rbp]
	mov	rax, QWORD PTR [rax+8]
	mov	rcx, QWORD PTR p_anim$[rbp]
	mov	rax, QWORD PTR [rax+16]
	mov	QWORD PTR [rcx+8], rax

; 96   :     p_anim->timer = p_anim->current->frame_time;

	mov	rax, QWORD PTR p_anim$[rbp]
	mov	rax, QWORD PTR [rax+8]
	mov	rcx, QWORD PTR p_anim$[rbp]
	mov	eax, DWORD PTR [rax+24]
	mov	DWORD PTR [rcx+24], eax

; 97   : }

	lea	rsp, QWORD PTR [rbp+200]
	pop	rdi
	pop	rbp
	ret	0
animation_step_forward ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File E:\CPP-Programming\Lama\Lama\Lama\main.c
;	COMDAT animation_animate
_TEXT	SEGMENT
p_anim$ = 224
animation_animate PROC					; COMDAT

; 84   : {

$LN4:
	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	push	rdi
	sub	rsp, 232				; 000000e8H
	lea	rbp, QWORD PTR [rsp+32]
	mov	rdi, rsp
	mov	ecx, 58					; 0000003aH
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	rcx, QWORD PTR [rsp+264]
	lea	rcx, OFFSET FLAT:__8BF91AE9_main@c
	call	__CheckForDebuggerJustMyCode

; 85   :     p_anim->timer--;

	mov	rax, QWORD PTR p_anim$[rbp]
	mov	eax, DWORD PTR [rax+24]
	dec	eax
	mov	rcx, QWORD PTR p_anim$[rbp]
	mov	DWORD PTR [rcx+24], eax

; 86   :     if(p_anim->timer < 0)

	mov	rax, QWORD PTR p_anim$[rbp]
	cmp	DWORD PTR [rax+24], 0
	jge	SHORT $LN2@animation_

; 87   :     {
; 88   :         p_anim->current = p_anim->current->next;

	mov	rax, QWORD PTR p_anim$[rbp]
	mov	rax, QWORD PTR [rax+8]
	mov	rcx, QWORD PTR p_anim$[rbp]
	mov	rax, QWORD PTR [rax+16]
	mov	QWORD PTR [rcx+8], rax

; 89   :         p_anim->timer = p_anim->current->frame_time;

	mov	rax, QWORD PTR p_anim$[rbp]
	mov	rax, QWORD PTR [rax+8]
	mov	rcx, QWORD PTR p_anim$[rbp]
	mov	eax, DWORD PTR [rax+24]
	mov	DWORD PTR [rcx+24], eax
$LN2@animation_:

; 90   :     }
; 91   : }

	lea	rsp, QWORD PTR [rbp+200]
	pop	rdi
	pop	rbp
	ret	0
animation_animate ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File E:\CPP-Programming\Lama\Lama\Lama\main.c
;	COMDAT animation_create
_TEXT	SEGMENT
anim$ = 8
frames$ = 72
index$ = 100
tv71 = 308
tv164 = 312
$T4 = 352
p_texture$ = 360
p_rects$ = 368
p_frame_count$ = 376
p_frame_time$ = 384
p_type$ = 392
animation_create PROC					; COMDAT

; 54   : {

$LN9:
	mov	DWORD PTR [rsp+32], r9d
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	push	rsi
	push	rdi
	sub	rsp, 352				; 00000160H
	lea	rbp, QWORD PTR [rsp+32]
	mov	rdi, rsp
	mov	ecx, 88					; 00000058H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	rcx, QWORD PTR [rsp+392]
	lea	rcx, OFFSET FLAT:__8BF91AE9_main@c
	call	__CheckForDebuggerJustMyCode

; 55   :     animation       anim; 
; 56   :     struct frame*   frames;
; 57   :     int             index;
; 58   : 
; 59   :     frames          = (struct frame*)calloc(p_frame_count, sizeof(struct frame));

	movsxd	rax, DWORD PTR p_frame_count$[rbp]
	mov	edx, 32					; 00000020H
	mov	rcx, rax
	call	QWORD PTR __imp_calloc
	mov	QWORD PTR frames$[rbp], rax

; 60   :     anim.current    = frames;

	mov	rax, QWORD PTR frames$[rbp]
	mov	QWORD PTR anim$[rbp+8], rax

; 61   :     anim.frames     = frames;

	mov	rax, QWORD PTR frames$[rbp]
	mov	QWORD PTR anim$[rbp+16], rax

; 62   :     anim.texture    = p_texture;

	mov	rax, QWORD PTR p_texture$[rbp]
	mov	QWORD PTR anim$[rbp], rax

; 63   :     anim.timer      = p_frame_time;

	mov	eax, DWORD PTR p_frame_time$[rbp]
	mov	DWORD PTR anim$[rbp+24], eax

; 64   : 
; 65   :     switch(p_type)

	mov	eax, DWORD PTR p_type$[rbp]
	mov	DWORD PTR tv71[rbp], eax
	cmp	DWORD PTR tv71[rbp], 0
	je	SHORT $LN7@animation_
	jmp	$LN2@animation_
$LN7@animation_:

; 66   :     {
; 67   :         case LOOP:
; 68   :         // Create the animation in here
; 69   :             for(index = 0; index < p_frame_count - 1; index++) //loop through all frames until the last one

	mov	DWORD PTR index$[rbp], 0
	jmp	SHORT $LN6@animation_
$LN4@animation_:
	mov	eax, DWORD PTR index$[rbp]
	inc	eax
	mov	DWORD PTR index$[rbp], eax
$LN6@animation_:
	mov	eax, DWORD PTR p_frame_count$[rbp]
	dec	eax
	cmp	DWORD PTR index$[rbp], eax
	jge	SHORT $LN5@animation_

; 70   :             {
; 71   :                 frames[index].rect          = p_rects[index];

	movsxd	rax, DWORD PTR index$[rbp]
	imul	rax, rax, 16
	movsxd	rcx, DWORD PTR index$[rbp]
	imul	rcx, rcx, 32				; 00000020H
	mov	rdx, QWORD PTR frames$[rbp]
	mov	r8, QWORD PTR p_rects$[rbp]
	lea	rdi, QWORD PTR [rdx+rcx]
	lea	rsi, QWORD PTR [r8+rax]
	mov	ecx, 16
	rep movsb

; 72   :                 frames[index].frame_time    = p_frame_time;

	movsxd	rax, DWORD PTR index$[rbp]
	imul	rax, rax, 32				; 00000020H
	mov	rcx, QWORD PTR frames$[rbp]
	mov	edx, DWORD PTR p_frame_time$[rbp]
	mov	DWORD PTR [rcx+rax+24], edx

; 73   :                 frames[index].next          = &frames[index + 1];

	mov	eax, DWORD PTR index$[rbp]
	inc	eax
	cdqe
	imul	rax, rax, 32				; 00000020H
	mov	rcx, QWORD PTR frames$[rbp]
	add	rcx, rax
	mov	rax, rcx
	movsxd	rcx, DWORD PTR index$[rbp]
	imul	rcx, rcx, 32				; 00000020H
	mov	rdx, QWORD PTR frames$[rbp]
	mov	QWORD PTR [rdx+rcx+16], rax

; 74   :             }

	jmp	SHORT $LN4@animation_
$LN5@animation_:

; 75   :             frames[index].rect          = p_rects[index];

	movsxd	rax, DWORD PTR index$[rbp]
	imul	rax, rax, 16
	movsxd	rcx, DWORD PTR index$[rbp]
	imul	rcx, rcx, 32				; 00000020H
	mov	rdx, QWORD PTR frames$[rbp]
	mov	rdi, QWORD PTR p_rects$[rbp]
	mov	QWORD PTR tv164[rbp], rdi
	lea	rdi, QWORD PTR [rdx+rcx]
	mov	rcx, QWORD PTR tv164[rbp]
	lea	rsi, QWORD PTR [rcx+rax]
	mov	ecx, 16
	rep movsb

; 76   :             frames[index].frame_time    = p_frame_time;

	movsxd	rax, DWORD PTR index$[rbp]
	imul	rax, rax, 32				; 00000020H
	mov	rcx, QWORD PTR frames$[rbp]
	mov	edx, DWORD PTR p_frame_time$[rbp]
	mov	DWORD PTR [rcx+rax+24], edx

; 77   :             frames[index].next          = frames;

	movsxd	rax, DWORD PTR index$[rbp]
	imul	rax, rax, 32				; 00000020H
	mov	rcx, QWORD PTR frames$[rbp]
	mov	rdx, QWORD PTR frames$[rbp]
	mov	QWORD PTR [rcx+rax+16], rdx
$LN2@animation_:

; 78   :         break;
; 79   :     }
; 80   :     return anim;

	lea	rax, QWORD PTR anim$[rbp]
	mov	rdi, QWORD PTR $T4[rbp]
	mov	rsi, rax
	mov	ecx, 32					; 00000020H
	rep movsb
	mov	rax, QWORD PTR $T4[rbp]

; 81   : }

	mov	rdi, rax
	lea	rcx, QWORD PTR [rbp-32]
	lea	rdx, OFFSET FLAT:animation_create$rtcFrameData
	call	_RTC_CheckStackVars
	mov	rax, rdi
	lea	rsp, QWORD PTR [rbp+320]
	pop	rdi
	pop	rsi
	pop	rbp
	ret	0
animation_create ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File E:\CPP-Programming\Lama\Lama\Lama\main.c
;	COMDAT error_msg
_TEXT	SEGMENT
msg$ = 224
error_msg PROC						; COMDAT

; 16   : {

$LN3:
	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	push	rdi
	sub	rsp, 232				; 000000e8H
	lea	rbp, QWORD PTR [rsp+32]
	mov	rdi, rsp
	mov	ecx, 58					; 0000003aH
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	rcx, QWORD PTR [rsp+264]
	lea	rcx, OFFSET FLAT:__8BF91AE9_main@c
	call	__CheckForDebuggerJustMyCode

; 17   :     printf("Error: %s \n", msg);

	mov	rdx, QWORD PTR msg$[rbp]
	lea	rcx, OFFSET FLAT:??_C@_0M@KMABGBDJ@Error?3?5?$CFs?5?6@
	call	printf

; 18   :     return -1;

	mov	eax, -1

; 19   : }

	lea	rsp, QWORD PTR [rbp+200]
	pop	rdi
	pop	rbp
	ret	0
error_msg ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt\time.h
;	COMDAT localtime_s
_TEXT	SEGMENT
_Tm$ = 224
_Time$ = 232
localtime_s PROC					; COMDAT

; 573  :             {

	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	push	rdi
	sub	rsp, 232				; 000000e8H
	lea	rbp, QWORD PTR [rsp+32]
	mov	rdi, rsp
	mov	ecx, 58					; 0000003aH
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	rcx, QWORD PTR [rsp+264]
	lea	rcx, OFFSET FLAT:__8AA3BE86_time@h
	call	__CheckForDebuggerJustMyCode

; 574  :                 return _localtime64_s(_Tm, _Time);

	mov	rdx, QWORD PTR _Time$[rbp]
	mov	rcx, QWORD PTR _Tm$[rbp]
	call	QWORD PTR __imp__localtime64_s

; 575  :             }

	lea	rsp, QWORD PTR [rbp+200]
	pop	rdi
	pop	rbp
	ret	0
localtime_s ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt\time.h
;	COMDAT time
_TEXT	SEGMENT
_Time$ = 224
time	PROC						; COMDAT

; 535  :         {

	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	push	rdi
	sub	rsp, 232				; 000000e8H
	lea	rbp, QWORD PTR [rsp+32]
	mov	rdi, rsp
	mov	ecx, 58					; 0000003aH
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	rcx, QWORD PTR [rsp+264]
	lea	rcx, OFFSET FLAT:__8AA3BE86_time@h
	call	__CheckForDebuggerJustMyCode

; 536  :             return _time64(_Time);

	mov	rcx, QWORD PTR _Time$[rbp]
	call	QWORD PTR __imp__time64

; 537  :         }

	lea	rsp, QWORD PTR [rbp+200]
	pop	rdi
	pop	rbp
	ret	0
time	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File E:\CPP-Programming\Lama\Lama\Lama\main.c
;	COMDAT SDL_main
_TEXT	SEGMENT
mouse_input$ = 8
window_settings$ = 56
event$ = 104
mouse_position_on_grid$ = 184
app$ = 216
grid_layer$ = 280
background_color$ = 340
alpha_color_key$ = 372
grass_source_rect$ = 408
grass_pool$ = 456
rawtime$ = 520
time_info$ = 552
texture$ = 584
surface$ = 616
window$ = 648
renderer$ = 680
running$ = 708
animation_step$ = 740
grass_index$ = 776
rects$ = 816
destination$ = 920
anim$ = 968
$T17 = 1608
$T18 = 1680
tv210 = 1700
__$ArrayPad$ = 1704
argc$ = 1744
argv$ = 1752
SDL_main PROC						; COMDAT

; 154  : {

$LN16:
	mov	QWORD PTR [rsp+16], rdx
	mov	DWORD PTR [rsp+8], ecx
	push	rbp
	push	rsi
	push	rdi
	sub	rsp, 1776				; 000006f0H
	lea	rbp, QWORD PTR [rsp+64]
	mov	rdi, rsp
	mov	ecx, 444				; 000001bcH
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	ecx, DWORD PTR [rsp+1816]
	mov	rax, QWORD PTR __security_cookie
	xor	rax, rbp
	mov	QWORD PTR __$ArrayPad$[rbp], rax
	lea	rcx, OFFSET FLAT:__8BF91AE9_main@c
	call	__CheckForDebuggerJustMyCode

; 155  :     mouse           mouse_input;
; 156  :     window_info     window_settings;
; 157  :     SDL_Event       event;
; 158  :     vector2         mouse_position_on_grid;
; 159  :     application     app;
; 160  :     grid            grid_layer;
; 161  :     SDL_Color       background_color;
; 162  :     Uint32          alpha_color_key;
; 163  :     SDL_Rect        grass_source_rect;
; 164  :     grass_field     grass_pool;
; 165  :     time_t          rawtime;
; 166  :     struct tm*      time_info               = NULL;

	mov	QWORD PTR time_info$[rbp], 0

; 167  :     SDL_Texture*    texture                 = NULL;

	mov	QWORD PTR texture$[rbp], 0

; 168  :     SDL_Surface*    surface                 = NULL;

	mov	QWORD PTR surface$[rbp], 0

; 169  :     SDL_Window*     window                  = NULL;

	mov	QWORD PTR window$[rbp], 0

; 170  :     SDL_Renderer*   renderer                = NULL;

	mov	QWORD PTR renderer$[rbp], 0

; 171  :     bool            running                 = true;

	mov	BYTE PTR running$[rbp], 1

; 172  :     int             animation_step          = 32;

	mov	DWORD PTR animation_step$[rbp], 32	; 00000020H

; 173  : 
; 174  :     // Set seed based on time
; 175  :     time(&rawtime);

	lea	rcx, QWORD PTR rawtime$[rbp]
	call	time

; 176  :     time_info = (struct tm*) malloc(sizeof(struct tm));

	mov	ecx, 36					; 00000024H
	call	QWORD PTR __imp_malloc
	mov	QWORD PTR time_info$[rbp], rax

; 177  :     localtime_s(time_info , &rawtime);

	lea	rdx, QWORD PTR rawtime$[rbp]
	mov	rcx, QWORD PTR time_info$[rbp]
	call	localtime_s

; 178  :     srand(time_info->tm_year + time_info->tm_mon + time_info->tm_min + time_info->tm_sec);

	mov	rax, QWORD PTR time_info$[rbp]
	mov	eax, DWORD PTR [rax+20]
	mov	rcx, QWORD PTR time_info$[rbp]
	add	eax, DWORD PTR [rcx+16]
	mov	rcx, QWORD PTR time_info$[rbp]
	add	eax, DWORD PTR [rcx+4]
	mov	rcx, QWORD PTR time_info$[rbp]
	add	eax, DWORD PTR [rcx]
	mov	ecx, eax
	call	QWORD PTR __imp_srand

; 179  :     
; 180  :     
; 181  : 
; 182  :     if(SDL_Init(SDL_INIT_EVERYTHING) != 0)

	mov	ecx, 62001				; 0000f231H
	call	SDL_Init
	test	eax, eax
	je	SHORT $LN8@SDL_main

; 183  :         return error_msg("Could not Initialise SDL");

	lea	rcx, OFFSET FLAT:??_C@_0BJ@JPHBGNOG@Could?5not?5Initialise?5SDL@
	call	error_msg
	jmp	$LN1@SDL_main
$LN8@SDL_main:

; 184  : 
; 185  :     memset(&mouse_input, NULL, sizeof(mouse_input));

	mov	r8d, 12
	xor	edx, edx
	lea	rcx, QWORD PTR mouse_input$[rbp]
	call	memset

; 186  : 
; 187  :     window_settings.title = "Lama";

	lea	rax, OFFSET FLAT:??_C@_04BLKNCPFJ@Lama@
	mov	QWORD PTR window_settings$[rbp], rax

; 188  :     window_settings.dimension.x = 640;

	mov	DWORD PTR window_settings$[rbp+16], 640	; 00000280H

; 189  :     window_settings.dimension.y = 640;

	mov	DWORD PTR window_settings$[rbp+20], 640	; 00000280H

; 190  :     window_settings.position.x = SDL_WINDOWPOS_CENTERED;

	mov	DWORD PTR window_settings$[rbp+8], 805240832 ; 2fff0000H

; 191  :     window_settings.position.y = SDL_WINDOWPOS_CENTERED;

	mov	DWORD PTR window_settings$[rbp+12], 805240832 ; 2fff0000H

; 192  :     
; 193  : 
; 194  :     if(!grid_init(&grid_layer, window_settings.dimension, 64, 0xFF0000FF))

	mov	r9d, -16776961				; ff0000ffH
	mov	r8d, 64					; 00000040H
	mov	rdx, QWORD PTR window_settings$[rbp+16]
	lea	rcx, QWORD PTR grid_layer$[rbp]
	call	grid_init
	movzx	eax, al
	test	eax, eax
	jne	SHORT $LN9@SDL_main

; 195  :         return error_msg("Could not initialise grid");

	lea	rcx, OFFSET FLAT:??_C@_0BK@OADPNOMO@Could?5not?5initialise?5grid@
	call	error_msg
	jmp	$LN1@SDL_main
$LN9@SDL_main:

; 196  : 
; 197  :     window = SDL_CreateWindow(window_settings.title,

	mov	DWORD PTR [rsp+40], 0
	mov	eax, DWORD PTR window_settings$[rbp+20]
	mov	DWORD PTR [rsp+32], eax
	mov	r9d, DWORD PTR window_settings$[rbp+16]
	mov	r8d, DWORD PTR window_settings$[rbp+12]
	mov	edx, DWORD PTR window_settings$[rbp+8]
	mov	rcx, QWORD PTR window_settings$[rbp]
	call	SDL_CreateWindow
	mov	QWORD PTR window$[rbp], rax

; 198  :                               window_settings.position.x,
; 199  :                               window_settings.position.y,
; 200  :                               window_settings.dimension.x,
; 201  :                               window_settings.dimension.y,
; 202  :                               NULL);
; 203  : 
; 204  :     renderer = SDL_CreateRenderer(window,

	xor	r8d, r8d
	xor	edx, edx
	mov	rcx, QWORD PTR window$[rbp]
	call	SDL_CreateRenderer
	mov	QWORD PTR renderer$[rbp], rax

; 205  :                                   NULL, 
; 206  :                                   NULL);
; 207  : 
; 208  : 
; 209  :     surface = SDL_LoadBMP("texture.bmp");

	lea	rdx, OFFSET FLAT:??_C@_02JDPG@rb@
	lea	rcx, OFFSET FLAT:??_C@_0M@INKEKBKD@texture?4bmp@
	call	SDL_RWFromFile
	mov	edx, 1
	mov	rcx, rax
	call	SDL_LoadBMP_RW
	mov	QWORD PTR surface$[rbp], rax

; 210  : 
; 211  :     alpha_color_key = (244 << 16) + (93 << 8) + (146 << 0);

	mov	DWORD PTR alpha_color_key$[rbp], 16014738 ; 00f45d92H

; 212  :     if(SDL_SetColorKey(surface, SDL_TRUE, alpha_color_key) != 0)

	mov	r8d, DWORD PTR alpha_color_key$[rbp]
	mov	edx, 1
	mov	rcx, QWORD PTR surface$[rbp]
	call	SDL_SetColorKey
	test	eax, eax
	je	SHORT $LN10@SDL_main

; 213  :         return error_msg("Surface not valid");

	lea	rcx, OFFSET FLAT:??_C@_0BC@DPMPNCOK@Surface?5not?5valid@
	call	error_msg
	jmp	$LN1@SDL_main
$LN10@SDL_main:

; 214  : 
; 215  :     texture = SDL_CreateTextureFromSurface(renderer, surface);

	mov	rdx, QWORD PTR surface$[rbp]
	mov	rcx, QWORD PTR renderer$[rbp]
	call	SDL_CreateTextureFromSurface
	mov	QWORD PTR texture$[rbp], rax

; 216  :     SDL_FreeSurface(surface);

	mov	rcx, QWORD PTR surface$[rbp]
	call	SDL_FreeSurface

; 217  : 
; 218  :     background_color.r = 214;

	mov	BYTE PTR background_color$[rbp], 214	; 000000d6H

; 219  :     background_color.g = 185;

	mov	BYTE PTR background_color$[rbp+1], 185	; 000000b9H

; 220  :     background_color.b = 123;

	mov	BYTE PTR background_color$[rbp+2], 123	; 0000007bH

; 221  :     background_color.a = 255;

	mov	BYTE PTR background_color$[rbp+3], 255	; 000000ffH

; 222  : 
; 223  :     app.grid_layer = &grid_layer;

	lea	rax, QWORD PTR grid_layer$[rbp]
	mov	QWORD PTR app$[rbp+16], rax

; 224  :     app.mouse_input = &mouse_input;

	lea	rax, QWORD PTR mouse_input$[rbp]
	mov	QWORD PTR app$[rbp+24], rax

; 225  :     app.renderer = renderer;

	mov	rax, QWORD PTR renderer$[rbp]
	mov	QWORD PTR app$[rbp], rax

; 226  :     app.window = window;

	mov	rax, QWORD PTR window$[rbp]
	mov	QWORD PTR app$[rbp+8], rax

; 227  : 
; 228  :     grass_source_rect.x = 0;

	mov	DWORD PTR grass_source_rect$[rbp], 0

; 229  :     grass_source_rect.y = 0;

	mov	DWORD PTR grass_source_rect$[rbp+4], 0

; 230  :     grass_source_rect.w = 32;

	mov	DWORD PTR grass_source_rect$[rbp+8], 32	; 00000020H

; 231  :     grass_source_rect.h = 32;

	mov	DWORD PTR grass_source_rect$[rbp+12], 32 ; 00000020H

; 232  : 
; 233  :     grass_field_init(&grass_pool,

	lea	rax, QWORD PTR $T18[rbp]
	lea	rcx, QWORD PTR grass_source_rect$[rbp]
	mov	rdi, rax
	mov	rsi, rcx
	mov	ecx, 16
	rep movsb
	mov	eax, DWORD PTR grid_layer$[rbp]
	mov	DWORD PTR [rsp+56], eax
	mov	eax, DWORD PTR animation_step$[rbp]
	mov	DWORD PTR [rsp+48], eax
	mov	DWORD PTR [rsp+40], 2000		; 000007d0H
	mov	DWORD PTR [rsp+32], 500			; 000001f4H
	lea	r9, QWORD PTR $T18[rbp]
	mov	r8, QWORD PTR grid_layer$[rbp+4]
	lea	rdx, QWORD PTR grid_layer$[rbp]
	lea	rcx, QWORD PTR grass_pool$[rbp]
	call	grass_field_init

; 234  :                            &grid_layer,
; 235  :                            grid_layer.dimensions,
; 236  :                            grass_source_rect,
; 237  :                            500,
; 238  :                            2000,
; 239  :                            animation_step,
; 240  :                            grid_layer.cell_size);
; 241  : 
; 242  :     vector2 grass_index = {4, 6};

	mov	DWORD PTR grass_index$[rbp], 4
	mov	DWORD PTR grass_index$[rbp+4], 6

; 243  : 
; 244  :     SDL_Rect rects[5] = { { 0, 0, 32, 32},

	mov	DWORD PTR rects$[rbp], 0
	mov	DWORD PTR rects$[rbp+4], 0
	mov	DWORD PTR rects$[rbp+8], 32		; 00000020H
	mov	DWORD PTR rects$[rbp+12], 32		; 00000020H
	mov	DWORD PTR rects$[rbp+16], 32		; 00000020H
	mov	DWORD PTR rects$[rbp+20], 0
	mov	DWORD PTR rects$[rbp+24], 32		; 00000020H
	mov	DWORD PTR rects$[rbp+28], 32		; 00000020H
	mov	DWORD PTR rects$[rbp+32], 64		; 00000040H
	mov	DWORD PTR rects$[rbp+36], 0
	mov	DWORD PTR rects$[rbp+40], 32		; 00000020H
	mov	DWORD PTR rects$[rbp+44], 32		; 00000020H
	mov	DWORD PTR rects$[rbp+48], 96		; 00000060H
	mov	DWORD PTR rects$[rbp+52], 0
	mov	DWORD PTR rects$[rbp+56], 32		; 00000020H
	mov	DWORD PTR rects$[rbp+60], 32		; 00000020H
	mov	DWORD PTR rects$[rbp+64], 128		; 00000080H
	mov	DWORD PTR rects$[rbp+68], 0
	mov	DWORD PTR rects$[rbp+72], 32		; 00000020H
	mov	DWORD PTR rects$[rbp+76], 32		; 00000020H

; 245  :                           { 32, 0, 32, 32},
; 246  :                           { 64, 0, 32, 32},
; 247  :                           { 96, 0, 32, 32},
; 248  :                           { 128, 0, 32, 32} };
; 249  : 
; 250  :     SDL_Rect destination = { 0, 0, 128, 128 };

	mov	DWORD PTR destination$[rbp], 0
	mov	DWORD PTR destination$[rbp+4], 0
	mov	DWORD PTR destination$[rbp+8], 128	; 00000080H
	mov	DWORD PTR destination$[rbp+12], 128	; 00000080H

; 251  : 
; 252  :     animation anim = animation_create(texture, rects, 5, 200, LOOP);

	mov	DWORD PTR [rsp+40], 0
	mov	DWORD PTR [rsp+32], 200			; 000000c8H
	mov	r9d, 5
	lea	r8, QWORD PTR rects$[rbp]
	mov	rdx, QWORD PTR texture$[rbp]
	lea	rcx, QWORD PTR $T17[rbp]
	call	animation_create
	lea	rcx, QWORD PTR anim$[rbp]
	mov	rdi, rcx
	mov	rsi, rax
	mov	ecx, 32					; 00000020H
	rep movsb
$LN2@SDL_main:

; 253  : 
; 254  :     while(running)

	movzx	eax, BYTE PTR running$[rbp]
	test	eax, eax
	je	$LN3@SDL_main
$LN4@SDL_main:

; 255  :     {
; 256  :         // Input Events
; 257  :         while(SDL_PollEvent(&event))

	lea	rcx, QWORD PTR event$[rbp]
	call	SDL_PollEvent
	test	eax, eax
	je	SHORT $LN5@SDL_main

; 258  :         {
; 259  :             switch(event.type)

	mov	eax, DWORD PTR event$[rbp]
	mov	DWORD PTR tv210[rbp], eax
	cmp	DWORD PTR tv210[rbp], 1024		; 00000400H
	jb	SHORT $LN6@SDL_main
	cmp	DWORD PTR tv210[rbp], 1026		; 00000402H
	jbe	SHORT $LN11@SDL_main
	jmp	SHORT $LN6@SDL_main
$LN11@SDL_main:

; 260  :             {
; 261  :                 case SDL_MOUSEMOTION:
; 262  :                 case SDL_MOUSEBUTTONDOWN:
; 263  :                 case SDL_MOUSEBUTTONUP:
; 264  :                 mouse_input.buttons = SDL_GetMouseState(&mouse_input.position.x, 

	lea	rdx, QWORD PTR mouse_input$[rbp+4]
	lea	rcx, QWORD PTR mouse_input$[rbp]
	call	SDL_GetMouseState
	mov	DWORD PTR mouse_input$[rbp+8], eax
$LN6@SDL_main:

; 265  :                                                         &mouse_input.position.y);
; 266  :                 break;
; 267  :             }
; 268  :         }

	jmp	SHORT $LN4@SDL_main
$LN5@SDL_main:

; 269  :         if(mouse_input.buttons & LEFT_CLICK)

	mov	eax, DWORD PTR mouse_input$[rbp+8]
	and	eax, 1
	test	eax, eax
	je	SHORT $LN12@SDL_main

; 270  :         {
; 271  :             mouse_position_on_grid.x = (int)(mouse_input.position.x / grid_layer.cell_size);

	mov	eax, DWORD PTR mouse_input$[rbp]
	cdq
	idiv	DWORD PTR grid_layer$[rbp]
	mov	DWORD PTR mouse_position_on_grid$[rbp], eax

; 272  :             mouse_position_on_grid.y = (int)(mouse_input.position.y / grid_layer.cell_size);

	mov	eax, DWORD PTR mouse_input$[rbp+4]
	cdq
	idiv	DWORD PTR grid_layer$[rbp]
	mov	DWORD PTR mouse_position_on_grid$[rbp+4], eax

; 273  : 
; 274  :             grass_field_toggle_active_at(&grass_pool, mouse_position_on_grid, true);

	mov	r8b, 1
	mov	rdx, QWORD PTR mouse_position_on_grid$[rbp]
	lea	rcx, QWORD PTR grass_pool$[rbp]
	call	grass_field_toggle_active_at

; 275  :             //set_grid_data_at(&grid_layer, 
; 276  :             //                 mouse_position_on_grid, 
; 277  :             //                 GRASS, 
; 278  :             //                 true);
; 279  :         }

	jmp	SHORT $LN13@SDL_main
$LN12@SDL_main:

; 280  :         else if(mouse_input.buttons & RIGHT_CLICK)

	mov	eax, DWORD PTR mouse_input$[rbp+8]
	and	eax, 4
	test	eax, eax
	je	SHORT $LN14@SDL_main

; 281  :         {
; 282  :             mouse_position_on_grid.x = (int)(mouse_input.position.x / grid_layer.cell_size);

	mov	eax, DWORD PTR mouse_input$[rbp]
	cdq
	idiv	DWORD PTR grid_layer$[rbp]
	mov	DWORD PTR mouse_position_on_grid$[rbp], eax

; 283  :             mouse_position_on_grid.y = (int)(mouse_input.position.y / grid_layer.cell_size);

	mov	eax, DWORD PTR mouse_input$[rbp+4]
	cdq
	idiv	DWORD PTR grid_layer$[rbp]
	mov	DWORD PTR mouse_position_on_grid$[rbp+4], eax

; 284  :             grass_field_toggle_active_at(&grass_pool, mouse_position_on_grid, false);

	xor	r8d, r8d
	mov	rdx, QWORD PTR mouse_position_on_grid$[rbp]
	lea	rcx, QWORD PTR grass_pool$[rbp]
	call	grass_field_toggle_active_at
$LN14@SDL_main:
$LN13@SDL_main:

; 285  :             //set_grid_data_at(&grid_layer, 
; 286  :             //                 mouse_position_on_grid, 
; 287  :             //                 GRASS, 
; 288  :             //                 false);
; 289  :         }
; 290  : 
; 291  :         // !Input Events
; 292  : 
; 293  :         // Update
; 294  :         grass_field_update(&grass_pool,

	lea	rdx, QWORD PTR grid_layer$[rbp]
	lea	rcx, QWORD PTR grass_pool$[rbp]
	call	grass_field_update

; 295  :                            &grid_layer);
; 296  :         // !Update
; 297  : 
; 298  :         // Render
; 299  :         SDL_SetRenderDrawColor(renderer,

	movzx	eax, BYTE PTR background_color$[rbp+3]
	mov	BYTE PTR [rsp+32], al
	movzx	r9d, BYTE PTR background_color$[rbp+2]
	movzx	r8d, BYTE PTR background_color$[rbp+1]
	movzx	edx, BYTE PTR background_color$[rbp]
	mov	rcx, QWORD PTR renderer$[rbp]
	call	SDL_SetRenderDrawColor

; 300  :                                background_color.r,
; 301  :                                background_color.g,
; 302  :                                background_color.b,
; 303  :                                background_color.a);
; 304  :         SDL_RenderClear(renderer);

	mov	rcx, QWORD PTR renderer$[rbp]
	call	SDL_RenderClear

; 305  : 
; 306  :         grass_field_draw(renderer,

	mov	r9, QWORD PTR grid_layer$[rbp+4]
	lea	r8, QWORD PTR grass_pool$[rbp]
	mov	rdx, QWORD PTR texture$[rbp]
	mov	rcx, QWORD PTR renderer$[rbp]
	call	grass_field_draw

; 307  :                         texture,
; 308  :                         &grass_pool,
; 309  :                         grid_layer.dimensions);
; 310  : 
; 311  :         grid_draw(renderer, &grid_layer);

	lea	rdx, QWORD PTR grid_layer$[rbp]
	mov	rcx, QWORD PTR renderer$[rbp]
	call	grid_draw

; 312  : 
; 313  :         animation_animate(&anim);

	lea	rcx, QWORD PTR anim$[rbp]
	call	animation_animate

; 314  :         animation_draw(renderer, &anim, &destination);

	lea	r8, QWORD PTR destination$[rbp]
	lea	rdx, QWORD PTR anim$[rbp]
	mov	rcx, QWORD PTR renderer$[rbp]
	call	animation_draw

; 315  : 
; 316  :         SDL_RenderPresent(renderer);

	mov	rcx, QWORD PTR renderer$[rbp]
	call	SDL_RenderPresent

; 317  :         // !Render
; 318  :     }

	jmp	$LN2@SDL_main
$LN3@SDL_main:

; 319  : 
; 320  :     grass_field_clean(&grass_pool);

	lea	rcx, QWORD PTR grass_pool$[rbp]
	call	grass_field_clean

; 321  :     grid_free_nodes(&grid_layer);

	lea	rcx, QWORD PTR grid_layer$[rbp]
	call	grid_free_nodes

; 322  : 
; 323  :     SDL_Quit();

	call	SDL_Quit

; 324  : 
; 325  :     return 0;

	xor	eax, eax
$LN1@SDL_main:

; 326  : }

	mov	rdi, rax
	lea	rcx, QWORD PTR [rbp-64]
	lea	rdx, OFFSET FLAT:SDL_main$rtcFrameData
	call	_RTC_CheckStackVars
	mov	rax, rdi
	mov	rcx, QWORD PTR __$ArrayPad$[rbp]
	xor	rcx, rbp
	call	__security_check_cookie
	lea	rsp, QWORD PTR [rbp+1712]
	pop	rdi
	pop	rsi
	pop	rbp
	ret	0
SDL_main ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt\stdio.h
;	COMDAT printf
_TEXT	SEGMENT
_Result$ = 4
_ArgList$ = 40
__$ArrayPad$ = 248
_Format$ = 288
printf	PROC						; COMDAT

; 954  :     {

$LN3:
	mov	QWORD PTR [rsp+8], rcx
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+32], r9
	push	rbp
	push	rdi
	sub	rsp, 296				; 00000128H
	lea	rbp, QWORD PTR [rsp+32]
	mov	rdi, rsp
	mov	ecx, 74					; 0000004aH
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	rcx, QWORD PTR [rsp+328]
	mov	rax, QWORD PTR __security_cookie
	xor	rax, rbp
	mov	QWORD PTR __$ArrayPad$[rbp], rax
	lea	rcx, OFFSET FLAT:__AD6A91B7_stdio@h
	call	__CheckForDebuggerJustMyCode

; 955  :         int _Result;
; 956  :         va_list _ArgList;
; 957  :         __crt_va_start(_ArgList, _Format);

	lea	rax, QWORD PTR _Format$[rbp+8]
	mov	QWORD PTR _ArgList$[rbp], rax

; 958  :         _Result = _vfprintf_l(stdout, _Format, NULL, _ArgList);

	mov	ecx, 1
	call	QWORD PTR __imp___acrt_iob_func
	mov	r9, QWORD PTR _ArgList$[rbp]
	xor	r8d, r8d
	mov	rdx, QWORD PTR _Format$[rbp]
	mov	rcx, rax
	call	_vfprintf_l
	mov	DWORD PTR _Result$[rbp], eax

; 959  :         __crt_va_end(_ArgList);

	mov	QWORD PTR _ArgList$[rbp], 0

; 960  :         return _Result;

	mov	eax, DWORD PTR _Result$[rbp]

; 961  :     }

	mov	edi, eax
	lea	rcx, QWORD PTR [rbp-32]
	lea	rdx, OFFSET FLAT:printf$rtcFrameData
	call	_RTC_CheckStackVars
	mov	eax, edi
	mov	rcx, QWORD PTR __$ArrayPad$[rbp]
	xor	rcx, rbp
	call	__security_check_cookie
	lea	rsp, QWORD PTR [rbp+264]
	pop	rdi
	pop	rbp
	ret	0
printf	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt\stdio.h
;	COMDAT _vfprintf_l
_TEXT	SEGMENT
_Stream$ = 224
_Format$ = 232
_Locale$ = 240
_ArgList$ = 248
_vfprintf_l PROC					; COMDAT

; 642  :     {

$LN3:
	mov	QWORD PTR [rsp+32], r9
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	push	rdi
	sub	rsp, 248				; 000000f8H
	lea	rbp, QWORD PTR [rsp+48]
	mov	rdi, rsp
	mov	ecx, 62					; 0000003eH
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	rcx, QWORD PTR [rsp+280]
	lea	rcx, OFFSET FLAT:__AD6A91B7_stdio@h
	call	__CheckForDebuggerJustMyCode

; 643  :         return __stdio_common_vfprintf(_CRT_INTERNAL_LOCAL_PRINTF_OPTIONS, _Stream, _Format, _Locale, _ArgList);

	call	__local_stdio_printf_options
	mov	rcx, QWORD PTR _ArgList$[rbp]
	mov	QWORD PTR [rsp+32], rcx
	mov	r9, QWORD PTR _Locale$[rbp]
	mov	r8, QWORD PTR _Format$[rbp]
	mov	rdx, QWORD PTR _Stream$[rbp]
	mov	rcx, QWORD PTR [rax]
	call	QWORD PTR __imp___stdio_common_vfprintf

; 644  :     }

	lea	rsp, QWORD PTR [rbp+200]
	pop	rdi
	pop	rbp
	ret	0
_vfprintf_l ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt\corecrt_stdio_config.h
;	COMDAT __local_stdio_printf_options
_TEXT	SEGMENT
__local_stdio_printf_options PROC			; COMDAT

; 86   :     {

$LN3:
	push	rbp
	push	rdi
	sub	rsp, 232				; 000000e8H
	lea	rbp, QWORD PTR [rsp+32]
	mov	rdi, rsp
	mov	ecx, 58					; 0000003aH
	mov	eax, -858993460				; ccccccccH
	rep stosd
	lea	rcx, OFFSET FLAT:__F66CEB67_corecrt_stdio_config@h
	call	__CheckForDebuggerJustMyCode

; 87   :         static unsigned __int64 _OptionsStorage;
; 88   :         return &_OptionsStorage;

	lea	rax, OFFSET FLAT:?_OptionsStorage@?1??__local_stdio_printf_options@@9@9 ; `__local_stdio_printf_options'::`2'::_OptionsStorage

; 89   :     }

	lea	rsp, QWORD PTR [rbp+200]
	pop	rdi
	pop	rbp
	ret	0
__local_stdio_printf_options ENDP
_TEXT	ENDS
END
